import type { Metadata } from "next";
import Link from 'next/link';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <header>
          <Link href={`/`}>index</Link>
          &nbsp;
          <Link href={`/search`}>search</Link>
          &nbsp;
          <Link href={`/book/1`}>book/1</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
